### ISSUE TITLE
Access Denied when editing file on Windows nodes

### ISSUE THREAD

**Issue by mlcooper** [martinb3/xmledit-cookbook#10]
I am getting an access denied message when editing a file on a Windows node.  The Administrator user and Administrators group have full access to the xml file in question.

The diff is large so I will trucate it.  The reason why I'm opening an issue is because of the Resource Declaration section in the error below; it is referencing the xmledit cookbook - I am not running into this error when editing xml on Linux nodes.

I verified the config.xml file is already in place.

```================================================================================
Error executing action `create` on resource 'file[d:/servicenow/<redacted>dev1/agent/config.xml]'
================================================================================

Errno::EACCES
-------------
Permission denied - d:/servicenow/<redacted>dev1/agent/config.xml

Cookbook Trace:
---------------
c:/chef/cache/cookbooks/xmledit/libraries/xmledit.rb:181:in `write_document'
c:/chef/cache/cookbooks/xmledit/libraries/xmledit.rb:52:in `action_bulk'

Resource Declaration:
---------------------
# In c:/chef/cache/cookbooks/xmledit/libraries/xmledit.rb

175:       resource = file resource_name do
176:         path file_to_write
177:         content new_file_contents
178:         action :nothing
179:       end
180:

Compiled Resource:
------------------
# Declared in c:/chef/cache/cookbooks/xmledit/libraries/xmledit.rb:175:in `write_document'

file("d:/servicenow/<redacted>dev1/agent/config.xml") do
  provider Chef::Provider::File
  action [:nothing]
  retries 0
  retry_delay 2
  guard_interpreter :default
  path "d:/servicenow/<redacted>dev1/agent/config.xml"
  backup 5
  atomic_update true
  diff "--- d:/servicenow/<redacted>dev1/agent/config.xml\t2015-05-25 09:59:24.000000000 -0700\\n+++ C```

**Comment by martinb3** [comment]
Hi there -- this is coming from Chef's built-in [`file` provider](https://docs.chef.io/resource_file.html). The xmledit cookbook is simply calling Chef's built in classes for writing files.

Can you test if a regular file resource is able to write to this file? Something like:
```
file '<path>' do
  content "foo"
end
```

**Comment by mlcooper** [comment]
This bit of code below does work successfully.  I ran it just before the xmledit block of code:

```
file "#{config_xml}" do
    content 'added from content'
end
```

After the chef run, the contents of the config.xml file were "added from content".

**Comment by martinb3** [comment]
After checking the line numbers in your error message, they don't correspond to what I'd expect -- are you using the latest version of this cookbook?

**Comment by mlcooper** [comment]
Hey Martin - I checked my Chef server and the only version that's uploaded to it is 1.2.1.

**Comment by mlcooper** [comment]
I see what you mean about this coming from Chef's File resource.  Opscode said this might be an issue with the client I'm using - 11.18.6.  We're working on diagnosing the issue.

**Comment by martinb3** [comment]
Thank you for the update @mlcooper. Please keep us posted.

**Comment by mlcooper** [comment]
Opscode suggested this might be a chef client 11.x issue that is fixed in Chef 12.  I tried Chef 12.3.0 on this Windows node and the error message did change...I have sent it to opscode.  Thought I'd share.

```
Recipe: <cookbook_name>::mid
  * cookbook_file[config.xml] action create (skipped due to not_if)
  * xml_edit[d:/servicenow/<depricated>dev1/agent/config.xml] action bulk

    ================================================================================
    Error executing action `bulk` on resource 'xml_edit[d:/servicenow/<depricated>dev1/agent/config.xml]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `file' for #<Chef::Provider::XmlEdit:0x6a79868>

    Cookbook Trace:
    ---------------
    C:/chef/cache/cookbooks/xmledit/libraries/xmledit.rb:175:in `write_document'
    C:/chef/cache/cookbooks/xmledit/libraries/xmledit.rb:52:in `action_bulk'

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/<cookbook_name>/recipes/mid.rb

    179:   xml_edit "#{config_xml}" do
    180:     edits [
    181:       { action: :replace,
    182:         target: "//parameters/parameter[@name='url']",
    183:         fragment: "<parameter name=\"url\" value=\"#{endpoints[instance]}\"/>"
    184:       },
    185:       { action: :replace,
    186:         target: "//parameters/parameter[@name='mid.instance.username']",
    187:         fragment: "<parameter name=\"mid.instance.username\" value=\"#{node[
    188:           '<cookbook_name>']['config_xml']['mid.instance.username'][
    189:           'value']}\"/>"
    190:       },
    191:       { action: :replace,
    192:         target: "//parameters/parameter[@name='mid.instance.password']",
    193:         fragment: "<parameter encrypt=\"true\" name=\"mid.instance.password\"
    194:           value=\"#{node['<cookbook_name>']['config_xml'][
    195:           'mid.instance.password']['value']}\"/>"
    196:       },
    197:       { action: :replace,
    198:         target: "//parameters/parameter[@name='name']",
    199:         fragment: "<parameter name=\"name\" value=\"#{node['<cookbook_name>'][
    200:           'config_xml']['name']['value']}\"/>"
    201:       },
    202:       { action: :replace,
    203:         target: "//parameters/parameter[@name='threads.max']",
    204:         fragment: "<parameter name=\"threads.max\" value=\"#{node[
    205:           '<cookbook_name>']['config_xml']['threads.max']['value']}\"/>"
    206:       },
    207:       { action: :replace,
    208:         target: "//parameters/parameter[@name='mid.proxy.use_proxy']",
    209:         fragment: "<parameter name=\"mid.proxy.use_proxy\" value=\"#{node[
    210:           '<cookbook_name>']['config_xml']['mid.proxy.use_proxy']['value']}\"/>"
    211:       },
    212:       { action: :replace,
    213:         target: "//parameters/parameter[@name='mid.proxy.host']",
    214:         fragment: "<parameter name=\"mid.proxy.host\" value=\"#{node[
    215:           '<cookbook_name>']['config_xml']['mid.proxy.host']['value']}\"/>"
    216:       },
    217:       { action: :replace,
    218:         target: "//parameters/parameter[@name='mid.proxy.port']",
    219:         fragment: "<parameter name=\"mid.proxy.port\" value=\"#{node[
    220:           '<cookbook_name>']['config_xml']['mid.proxy.port']['value']}\"/>"
    221:       },
    222:       { action: :replace,
    223:         target: "//parameters/parameter[@name='mid_sys_id']",
    224:         fragment: "<parameter name=\"mid_sys_id\" value=\"#{node[
    225:           '<cookbook_name>']['config_xml']['mid_sys_id']['value']}\"/>"
    226:       }
    227:     ]
    228:     action :bulk
    229:     notifies :restart, "service[mid-#{app_name}]"
    230:   end
    231:

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/<cookbook_name>/recipes/mid.rb:179:in `block in from_file'

    xml_edit("d:/servicenow/<depricated>dev1/agent/config.xml") do
      action [:bulk]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :xml_edit
      cookbook_name "<cookbook_name>"
      recipe_name "mid"
      edits [<truncated>]
      path "d:/servicenow/<depricated>dev1/agent/config.xml"
      bind_root_namespace true
    end

  * windows_service[mid-<depricated>dev1] action start
```

**Comment by martinb3** [comment]
`C:/chef/cache/cookbooks/xmledit/libraries/xmledit.rb:175:in `write_document'` -- that's off. Line 175 is a comment in the current version.

**Comment by martinb3** [comment]
Could you share your Berksfile.lock? I'm only interested in lines matching `xmledit` or `poise`, if you want to strip out the rest so you don't have to censor it.

**Comment by mlcooper** [comment]
I'm still on v1.2.1 of the xmledit cookbook.  That's the only version uploaded to the chef server.  I'm not sure why newer stuff is in the Berksfile.lock info below to be honest with you.  This is from the root of the cookbook that uses xmledit.
```
twdc_servicenow (0.4.2)
    nokogiri (~> 0.1.4)
    twdc_chef_node (~> 3.3)
    twdc_zipp (~> 1.3)
    xmledit (~> 1.2)
xmledit (1.2.2)
    poise (>= 0.0.0)
    xml (>= 0.0.0)
```

**Comment by martinb3** [comment]
I usually see folks use `berks apply <environment>` so their Berksfile.lock is usually in lockstep with what's on the chef server. Can you share the same information about poise on your chef server as well? FWIW, xmledit 1.2.1 and older worked with poise 1.x, and xmledit 1.2.3 added support / moved to poise 2.x. We're actually doing CI with chef 12 on this cookbook, so I don't _think_ it's broken on Chef 12 on Linux. This is very odd.

**Comment by mlcooper** [comment]
The only version of the poise cookbook uploaded to my chef server is currently 1.0.10.  

On Linux with client 11.18.6...no issues using xmledit.  Just Windows...

**Comment by mlcooper** [comment]
I will be without email access until June 9th.  Opscode is currently analyzing the error that was generated with the Chef 12 client.

**Comment by martinb3** [comment]
@mlcooper Could this be a case where your temporary directory is on a different device than where your XML file is, or if you have a virus scanner? I recently saw a similar case: https://github.com/berkshelf/berkshelf/issues/140#issuecomment-9846986

**Comment by mlcooper** [comment]
I just ran the chef run again with ProcessMonitor running at the same time to watch what's happening.  I do not see any ACCESS DENIED messages in processmonitor, and in fact I do see it working with the file in the Temp directory during the xmledit work.  Opscode continues to investigate and I will send them this info.  We do have A/V software installed of course, but in the past haven't seen it cause any issues like this.  I will see if I can see anything in its logs.

**Comment by devnuller** [comment]
I believe I may have found the problem. This code:
 def write_document
      old_file_contents = ::File.open(new_resource.path).read
      new_file_contents = document_to_string(document)


The line with "old_file_contents =" actually leaves a file descriptor to the target file open until this variable goes out of scope. The chef file resource opens another file descriptor to the same filename, resulting in the EACCESS problem.

I made some tweaks in version 1.1.0 to do something along these lines:
      f = ::File.open(new_resource.path)
      old_file_contents = f.read
      f.close()

For me, that fixed the problem instantly.

**Comment by martinb3** [comment]
@devnuller This is a nice find!

**Comment by martinb3** [comment]
I'll release a fix momentarily.

**Comment by martinb3** [comment]
I've released v1.2.4. @mlcooper can you give it a try and see if it fixes your issue?

**Comment by mlcooper** [comment]
I'm actually not able to upload 1.2.4 to my chef server due to the poise cookbook dependency of ``` ~> 2.0.0 ```.  Since poise 2.x is now a gem, I'm thinking that perhaps xmledit should install this gem and not have it as a cookbook dependency anymore.  The error I'm getting is:

```
$ knife cookbook upload xmledit
Uploading xmledit        [1.2.4]
ERROR: Cookbook xmledit depends on cookbooks which are not currently
ERROR: being uploaded and cannot be found on the server.
ERROR: The missing cookbook(s) are: 'poise' version '~> 2.0.0'
```

**Comment by devnuller** [comment]
bit of a side-step from the actual issue, but the poise dependency is also what is keeping me from upgrading to the latest greatest version of xml_edit

**Comment by martinb3** [comment]
I've released a major version bump (v2.0.0) that removes the poise dependency. Please let me know if that gets the issue taken care of for you both :)

**Comment by mlcooper** [comment]
The file is now being edited on my Windows node, so looks like it's working for me!  Thanks!!

**Comment by martinb3** [comment]
@mlcooper Glad it works! Sorry it took so long and so much digging to find that :)

**Comment by devnuller** [comment]
I'm also at 2.0.0 now and everything works like a charm. Thanks for this really useful cookbook
