### ISSUE TITLE
Bulk edit doesn't appear to be updating values.

### ISSUE THREAD

**Issue by mlcooper** [martinb3/xmledit-cookbook#9]
Doing a bulk edit doesn't appear to be updating values.  You can see that the **values are the same** after as they were before:

xml_edit[/servicenow/<redacted>uat/agent/config.xml] action bulk
     * file[/servicenow/<redacted>uat/agent/config.xml] action create
       - update content in file /servicenow/<redacted>uat/agent/config.xml from 289026 to 31c043
       --- /servicenow/<redacted>uat/agent/config.xml     2015-05-05 09:47:29.255852068 -0700
       +++ /tmp/.config.xml20150505-2037-rookm0       2015-05-05 09:47:29.282852201 -0700
       @@ -1,13 +1,14 @@
       -<?xml version="1.0" encoding="UTF-8"?>
       +<?xml version="1.0" encoding="UTF-8"?>
       +

       -   <parameter name="url" value="SN_ENDPOINT_URL" />
       -   <parameter name="mid.instance.username" value="SN_USERNAME" />
       -   <parameter encrypt="true" name="mid.instance.password" value="SN_PASSWORD" />
       -   <parameter name="name" value="MID_SERVER_NAME" />
       -   <parameter name="threads.max" value="" />
       -   <parameter name="mid.proxy.use_proxy" value="" />
       -   <parameter name="mid.proxy.host" value="" />
       -   <parameter name="mid.proxy.port" value="" />
       -   <parameter name="mid_sys_id" value="" />
       +  <parameter name="url" value="SN_ENDPOINT_URL"/>
       +  <parameter name="mid.instance.username" value="SN_USERNAME"/>
       +  <parameter encrypt="true" name="mid.instance.password" value="SN_PASSWORD"/>
       +  <parameter name="name" value="MID_SERVER_NAME"/>
       +  <parameter name="threads.max" value=""/>
       +  <parameter name="mid.proxy.use_proxy" value=""/>
       +  <parameter name="mid.proxy.host" value=""/>
       +  <parameter name="mid.proxy.port" value=""/>
       +  <parameter name="mid_sys_id" value=""/>
</parameters>

Here is the code I'm using to do the bulk update:

Chef::Log.info("MLC Endpoint: #{endpoints[instance]}, Username: #{node[
          'twdc_servicenow']['config_xml']['mid.instance.username'][
          'value']}")
  
  # edit config.xml file in order to configure it
  xml_edit "#{config_xml}" do
    edits [
      { action: :replace,
        target: "//parameters/parameter[@name='url']",
        fragment: "<parameter name=\"url\" value=\"#{endpoints[instance]}\"/>"
      },
      { action: :replace,
        target: "//parameters/parameter[@name='mid.instance.username']",
        fragment: "<parameter name=\"mid.instance.username\" value=\"#{node[
          'twdc_servicenow']['config_xml']['mid.instance.username'][
          'value']}\"/>"
      },
      { action: :replace,
        target: "//parameters/parameter[@name='mid.instance.password']",
        fragment: "<parameter encrypt=\"true\" name=\"mid.instance.password\"
          value=\"#{node['twdc_servicenow']['config_xml'][
          'mid.instance.password']['value']}\"/>"
      },
      { action: :replace,
        target: "//parameters/parameter[@name='name']",
        fragment: "<parameter name=\"name\" value=\"#{node['twdc_servicenow'][
          'config_xml']['name']['value']}\"/>"
      },
      { action: :replace,
        target: "//parameters/parameter[@name='threads.max']",
        fragment: "<parameter name=\"threads.max\" value=\"#{node[
          'twdc_servicenow']['config_xml']['threads.max']['value']}\"/>"
      },
      { action: :replace,
        target: "//parameters/parameter[@name='mid.proxy.use_proxy']",
        fragment: "<parameter name=\"mid.proxy.use_proxy\" value=\"#{node[
          'twdc_servicenow']['config_xml']['mid.proxy.use_proxy']['value']}\"/>"
      },
      { action: :replace,
        target: "//parameters/parameter[@name='mid.proxy.host']",
        fragment: "<parameter name=\"mid.proxy.host\" value=\"#{node[
          'twdc_servicenow']['config_xml']['mid.proxy.host']['value']}\"/>"
      },
      { action: :replace,
        target: "//parameters/parameter[@name='mid.proxy.port']",
        fragment: "<parameter name=\"mid.proxy.port\" value=\"#{node[
          'twdc_servicenow']['config_xml']['mid.proxy.port']['value']}\"/>"
      },
      { action: :replace,
        target: "//parameters/parameter[@name='mid_sys_id']",
        fragment: "<parameter name=\"mid_sys_id\" value=\"#{node[
          'twdc_servicenow']['config_xml']['mid_sys_id']['value']}\"/>"
      }
    ]
    action :bulk
  end

I inserted some logging into my recipe to ensure that the attributes were working (as you can see above) and I did get valid values for them.

**Comment by martinb3** [comment]
Thank you for the report @mlcooper -- there was a comment that snuck in there that shouldn't have been there. Please give it a try with the version I just released.
